   const images = [
        { img: "./thumbnail/1.webp", title: "Thumbnail design" ,  category:"finance"},
        { img: "./thumbnail/2.webp", title: "Thumbnail design" ,  category:"irl"},
        { img: "./thumbnail/3.webp", title: "Thumbnail design" ,  category:"football"},
        { img: "./thumbnail/4.webp", title: "Thumbnail design" ,  category:"finance"},
        { img: "./thumbnail/5.webp", title: "Thumbnail design" ,  category:"irl"},
        { img: "./thumbnail/6.webp", title: "Thumbnail design" ,  category:"irl"},
        { img: "./thumbnail/7.webp", title: "Thumbnail design" ,  category:"finance"},
        { img: "./thumbnail/8.webp", title: "Thumbnail design" ,  category:"football"},
        { img: "./thumbnail/9.webp", title: "Thumbnail design" ,  category:"football"},
        { img: "./thumbnail/10.webp", title: "Thumbnail design" , category:"other"},
        { img: "./thumbnail/11.webp", title: "Thumbnail design" , category:"other"},
        { img: "./thumbnail/12.webp", title: "Thumbnail design" , category:"other"},
        { img: "./thumbnail/13.webp", title: "Thumbnail design" , category:"football"},
        { img: "./thumbnail/14.webp", title: "Thumbnail design" , category:"other"},
        { img: "./thumbnail/15.webp", title: "Thumbnail design" , category:"irl"},
        { img: "./thumbnail/16.webp", title: "Thumbnail design" , category:"football"},
        { img: "./thumbnail/17.webp", title: "Thumbnail design" , category:"football"},
        { img: "./thumbnail/18.webp", title: "Thumbnail design" , category:"finance"},
        { img: "./thumbnail/19.webp", title: "Thumbnail design" , category:"finance"},
        { img: "./thumbnail/20.webp", title: "Thumbnail design" , category:"finance"},
        { img: "./thumbnail/21.webp", title: "Thumbnail design" , category:"other"},
        { img: "./thumbnail/22.webp", title: "Thumbnail design" , category:"football"},
        { img: "./thumbnail/23.webp", title: "Thumbnail design" , category:"football"},
        { img: "./thumbnail/24.webp", title: "Thumbnail design" , category:"other"},
        { img: "./thumbnail/25.webp", title: "Thumbnail design" , category:"other"},
        { img: "./thumbnail/26.webp", title: "Thumbnail design" , category:"other"},
        { img: "./thumbnail/27.webp", title: "Thumbnail design" , category:"football"},
        { img: "./thumbnail/28.webp", title: "Thumbnail design" , category:"irl"},
        { img: "./thumbnail/29.webp", title: "Thumbnail design" , category:"football"},
        { img: "./thumbnail/30.webp", title: "Thumbnail design" , category:"finance"},
        { img: "./thumbnail/31.webp", title: "Thumbnail design" , category:"finance"},
        { img: "./thumbnail/32.webp", title: "Thumbnail design" , category:"irl"},
        { img: "./thumbnail/33.webp", title: "Thumbnail design" , category:"irl"},
        { img: "./thumbnail/34.webp", title: "Thumbnail design" , category:"other"},
        { img: "./thumbnail/35.webp", title: "Thumbnail design" , category:"other"},
        { img: "./thumbnail/36.webp", title: "Thumbnail design" , category:"other"},

    ];
export default images;